#!/bin/bash
# drivers/usb/core
WD=$(dirname $0)
WD=$(cd $WD; pwd)
source ${WD}/kbuild_include.sh

SUBDIRS=${3:?"subdir to build from the kernel"}

cd ${KERNELDIR}
make EXTRAVERSION=${EXTRAVERSION} O=${WORKDIR} modules SUBDIRS=${SUBDIRS}

